config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection { post :import }
    get 'export' , to: 'users#export'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :title, presence: true
  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      user_hash = row.to_hash
      user = User.where(id: user_hash["id"])

      if user.count == 1
        user.first.update_attributes(user_hash)
      else
        User.create!(user_hash)
      end # end if !user.nil?
    end # end CSV.foreach
  end # end self.import(file)
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv.add_row column_names
      all.each do |foo|
        values = foo.attributes.values
      csv.add_row values
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def import
    begin
      User.import(params[:file])
      redirect_to root_url, notice: "Users imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end
  
  def export
    @users = User.all.order(:created_at)
    
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSV Importing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Application Name', root_path, :class => "navbar-brand" %>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav -left">
            <li><%= link_to 'List users', users_path %></li>
            <li><%= link_to 'New user', new_user_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:
      </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>  
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>  
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>  
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Editing User</h4>
    </div>
    <div class="panel-body">
        <%= render 'form', user: @user %>
    </div>
</div>

<%= link_to 'Back', users_path, :class => "btn btn-default" %>

app/views/users/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<div>
  <h1>List Users</h1>
  <%= link_to 'New User', new_user_path, :class => "btn btn-primary pull-right" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th><%= check_box_tag 'cbSelectAllUser' %></th>
      <th>Title</th>
      <th>Name</th>
      <th>Email</th>
      <th style="width: 145px"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= check_box_tag 'cbSelectUser', user.id %></td>
        <td><%= user.title %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), :class=>"btn btn-primary" %>
          <%= link_to 'Destroy', user, :class=>"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Export Data", user_export_path(@users, format: "csv"), :class => "btn btn-primary" %>

<script>
  $("#cbSelectAllUser").change(function(){
    var isCheck = false;
    if ($(this).prop('checked'))
      isCheck = true;
    if (isCheck) {
      $("input[name='cbSelectUser']").prop('checked', 'checked')
    } else {
      $("input[name='cbSelectUser']").removeAttr('checked')
    }
  });
</script>

app/views/users/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>New User</h4>
    </div>
    <div class="panel-body">
        <%= render 'form', user: @user %>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Import a CSV File</h4>
    </div>
    <div class="panel-body">
        <%= form_tag import_users_path, :class => 'form-horizontal', multipart: true do %>
          <div class="form-group">
              <%= label_tag "CSV file", nil, :class => "col-sm-2" %>
              <div class="col-sm-10">
                  <%= file_field_tag :file, :class => "" %>
              </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= submit_tag "Import CSV", :class => "btn btn-primary" %>
            </div>
          </div>
        <% end %>
    </div>
</div>

<%= link_to 'Back', users_path, :class => "btn btn-default" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>